In [3]:
import numpy as np
a=np.array([[1,2,4],[5,8,7]])
print("Array created:\n",a)
           

Array created:
 [[1 2 4]
 [5 8 7]]


In [4]:
b=np.zeros((3,4))
print("Array with all zeros:\n",b)

Array with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
c=np.full((3,3),6)
print("Array with all 6s:\n",c)

Array with all 6s:
 [[6 6 6]
 [6 6 6]
 [6 6 6]]


In [8]:
d=np.random.random((2,2))
print("Random aray:\n",d)

Random aray:
 [[0.02191721 0.84884008]
 [0.34861699 0.57030241]]


In [10]:
#create a sequence of integers from 0 to 30:
e=np.arange(0,30,5)
print(e)

[ 0  5 10 15 20 25]


In [12]:
#Reshaping 3*4 array to 2*2*3 array

arr=np.array([[1,2,3,4],[5,2,4,2],[1,2,0,1]])
new_arr=arr.reshape(4,3)
print("\n Original array:\n",arr)
print("Reshaped array[4,3]:\n",new_arr)


 Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Reshaped array[4,3]:
 [[1 2 3]
 [4 5 2]
 [4 2 1]
 [2 0 1]]


In [15]:
#flatten array

arr=np.array([[1,2,3,4],[5,2,4,2],[1,2,0,1]])
flarr=arr.flatten()
print("\nOriginal array:\n",arr)
print("\nflattened array:\n",flarr)




Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]

flattened array:
 [1 2 3 4 5 2 4 2 1 2 0 1]


In [16]:
print("\n No.of dimensions:\n",arr.ndim)
print("\nShape of array:\n",arr.shape)
print("\nSize of array:\n",arr.size)
print("\nArray type:\n",arr.dtype)
newtype=arr.astype('f')
print("\nConverted array element:\n",newtype)
print("\nConverted array type:\n",newtype.dtype)


 No.of dimensions:
 2

Shape of array:
 (3, 4)

Size of array:
 12

Array type:
 int64

Converted array element:
 [[1. 2. 3. 4.]
 [5. 2. 4. 2.]
 [1. 2. 0. 1.]]

Converted array type:
 float32


In [17]:
#slicing
p=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(p[3:0:-1])
print(p[2,0:2])
print(p[2:,2:])
print(p[1:,1])
c=p.astype('f')
print(c)

[[10 11 12]
 [ 7  8  9]
 [ 4  5  6]]
[7 8]
[[ 9]
 [12]
 [15]]
[ 5  8 11 14]
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]
 [13. 14. 15.]]
